---

- name: Add files    
  block:
    - name: 10 - Create directory
      file:
        path: "{{ project.project_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: true

    - name: 20 - Move docker-compose.yml
      synchronize:
        src: "{{ playbook_dir }}/docker-compose.yml"
        dest: "{{ project.project_path }}/docker-compose.yml"

    - name: 30 - Move files
      synchronize:
        src: "{{ playbook_dir }}/{{ item }}/"
        dest: "{{ project.project_path }}/{{ item }}/"
      with_items:
        - "flask_app"
        - "fetch_app"
        - "db_postgres"
        - "report_app"
        - "send_report"

    - name: 40 - Create .env file
      template:
        src: "{{ playbook_dir }}/ansible/templates/env.j2"
        dest: "{{ project.project_path }}/.env"
        mode: "0600"
      no_log: true

    - name: "50 - Ensure {{ project.project_path }} is owned by {{ ansible_user }} user and group"
      file:
        path: "{{ project.project_path }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
      become: true
          
        