---

- name: A - Install components
  hosts: aws 
  any_errors_fatal: true

  tasks:
    - name: 10 - Run install components role
      include_role:
        name: 020_install_components
        
  tags: ['install_components', 'full']


- name: B - Deploy Docker containers
  hosts: aws 
  any_errors_fatal: true

  tasks:
    - name: 10 - Run deploy docker role
      include_role:
        name: 030_deploy_docker

  tags: ['deploy_docker', 'full']
