services:
  db:
    image: postgres:15-alpine
    container_name: weatherdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  fetch_app:
    build: ./fetch_app
    container_name: fetch_app
    depends_on:
      - db
    environment:
      - OPENWEATHER_API_KEY
      - DB_HOST=db

  flask_app:
    build: ./flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    
  report_app:
    build: ./report_app
    container_name: report_app
    volumes:
      - ./output:/app/output
    depends_on:
      - db
    environment:
      - DB_HOST=db

  send_report:
    build: ./send_report
    container_name: send_report
    volumes:
      - ./output:/app/output
    depends_on:
      - db
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET

volumes:
  report_data: