services:
  db:
    image: postgres:15-alpine
    container_name: weatherdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  fetch_app:
    build: ./fetch_app
    container_name: fetch_app
    depends_on:
      - db

  flask_app:
    build: ./flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  report_app:
    build: ./report_app
    container_name: report_app
    volumes:
      - report_data:/app
    depends_on:
      - db

  send_report:
    build: ./send_report
    container_name: send_report
    volumes:
      - report_data:/app
    depends_on:
      - db

    
    