---

- name: Install components
  block:
    - name: 10 - Include project properties
      include_vars:
        file: "{{ playbook_dir }}/workspace/vars.yml"

    - name: 20 - Set docker_compose_url fact dynamically
      set_fact:
        docker_compose_url: "https://github.com/docker/compose/releases/download/latest/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"

    - name: 30 - Install pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present
      become: true

    # - name: Remove python3-urllib3 (to repair broken RPM)
    #   ansible.builtin.dnf:
    #     name: python3-urllib3
    #     state: absent
    #   become: true

    - name: Install python3-urllib3
      pip:
        name: urllib3
        executable: pip3
        state: present
      become: true

    - name: Install boto3
      pip:
        name: boto3
        executable: pip3
        state: present
      become: true

    # - name: Remove awscli (to repair broken RPM)
    #   ansible.builtin.dnf:
    #     name: awscli
    #     state: absent
    #   become: true

    - name: 40 - Check if AWS CLI is preinstalled
      ansible.builtin.command:
        cmd: aws --version
      register: aws_cli_version
      ignore_errors: true

    - name: 50 - Install AWS CLI
      ansible.builtin.dnf:
        name: awscli
        state: present
      become: true
      when: aws_cli_version.rc != 0

    - name: 70 - Install Docker Engine
      ansible.builtin.dnf:
        name: docker
        state: present
      become: true

    - name: 80 - Install Docker SDK for Python (for Ansible)
      pip:
        name: docker
        executable: pip3
        state: present
        extra_args: --ignore-installed
      become: true

    - name: Creates directory
      ansible.builtin.file:
        path: /usr/local/lib/docker/cli-plugins/
        state: directory
        mode: '0755'
      become: true

    - name: Download Docker Compose plugin binary
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'
      become: true

    - name: Ensure docker-compose is executable
      ansible.builtin.file:
        path: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'
        state: file
      become: true

    - name: 100 - Create a symbolic link
      file:
        src: /usr/local/lib/docker/cli-plugins/docker-compose
        dest: /usr/bin/docker-compose
        state: link
      become: true

    - name: 110 - Reload systemd configuration
      systemd:
        daemon_reload: yes
      become: true

    - name: 120 - Enable and start Docker services
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      become: true