---

- name: Install components
  block:
    - name: 10 - Include project properties
      include_vars:
        file: "{{ playbook_dir }}/workspace/vars.yml"

    - name: 20 - Set docker_compose_url fact dynamically
      set_fact:
        docker_compose_url: "https://github.com/docker/compose/releases/download/latest/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"

    - name: 30 - Install pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present
      become: true

    - name: 40 - Check if AWS CLI is preinstalled
      ansible.builtin.command:
        cmd: aws --version
      register: aws_cli_version
      ignore_errors: true

    - name: 50 - Install AWS CLI
      ansible.builtin.dnf:
        name: awscli
        state: present
      become: true
      when: aws_cli_version.rc != 0

    - name: 60 - Install Docker Engine
      dnf:
        name: docker
        state: present
      become: true

    - name: 70 - Install Docker SDK for Python (for Ansible)
      pip:
        name: docker
        executable: pip3
        state: present
      become: true

    - name: 80 - Install Docker Compose from github repo
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: true

    - name: 90 - Create a symbolic link
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
      become: true

    - name: 100 - Reload systemd configuration
      systemd:
        daemon_reload: yes
      become: true

    - name: 110 - Enable and start Docker services
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      become: true
