---

- name: Deploy docker
  block:
    - name: 10 - Include project properties
      include_vars:
        file: "{{ playbook_dir }}/workspace/vars.yml"

    - name: Copy docker-compose.yml
      copy:
        src: "{{ playbook_dir }}/../docker-compose.yml"
        dest: /home/{{ ansible_user }}/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Pull latest Docker images
      community.docker.docker_compose_v2:
        compose_file: /home/{{ ansible_user }}/docker-compose.yml
        state: present
        pull: true
      become: true

    - name: 20 - Deploy docker
      community.docker.docker_compose_v2:
        compose_file: /home/{{ ansible_user }}/docker-compose.yml
        state: present
      become: true