---

- name: Configure Jenkins
  block:
    - name: 10 - Include project properties
      include_vars:
        file: "{{ playbook_dir }}/workspace/vars.yml"

    - name: 20 - Include secret vars
      include_vars:
        file: "{{ playbook_dir }}/ansible/vars/secret_vars.yml"

    - name: Get Jenkins crumb
      uri:
        url: "http://{{ project.private_ip }}:8080/crumbIssuer/api/json"
        user: "{{ project.jenkins.user }}"
        password: "{{ jenkins_token }}"
        force_basic_auth: yes
        return_content: yes
      register: jenkins_crumb
      delegate_to: localhost

    - name: Start Jenkins pipeline
      uri:
        url: "http://{{ project.private_ip }}:8080/job/deploy_pipeline/build?delay=0sec"
        method: POST
        user: "{{ project.jenkins.user }}"
        password: "{{ jenkins_token }}"
        headers: "{{ {jenkins_crumb.json.crumbRequestField: jenkins_crumb.json.crumb} }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 201
      delegate_to: localhost
      register: result

    - name: 30 - query jenkins job queue to see if the build started
      block:
        - name: 30a - poll jenkins JOB QUEUE to see if the build started 
          uri:
            url: "http://{{ project.private_ip }}:8080/queue/api/json"
            force_basic_auth: true
            validate_certs: false
            method: GET
            user: "{{ project.jenkins.user }}"
            password: "{{ jenkins_token }}"
            return_content: true
            timeout: 3
          register: queue_response
          until: queue_response|json_query('json.executable.number')|default(0)|int > 0
          retries: 20
          delay: 2
      rescue:
        - name: 30b - fail if build did not start 
          fail:
            msg: "Error, could not query the jenkins job queue"

    - name: 40 - Checking if jenkins job is running
      uri:
        url: "http://{{ project.private_ip }}:8080/job/deploy_pipeline/queue_response.json.executable.number/api/json"
        force_basic_auth: true
        validate_certs: false
        method: GET
        user: "{{ project.jenkins.user }}"
        password: "{{ jenkins_token }}"
        return_content: true
        timeout: 3
      register: job_response
      until: job_response|json_query('json.building')|bool == false
      retries: 100
      delay: 30

    - name: 50 - Build job FAILED or ABORTED 
      fail: 
        msg: "Build job FAILED"
      when: 
        job_response|json_query('json.result') in ['FAILURE', 'ABORTED']
    
    - name: 60 - Build job SUCCESS
      debug:
        msg: "Build job SUCCESSFUL"
      when: 
        job_response|json_query('json.result') not in ['FAILURE', 'ABORTED']